apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-web-server.fullname" . }}
  labels:
    {{- include "simple-web-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "simple-web-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simple-web-server.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: {{ include "simple-web-server.fullname" . }}-data
          persistentVolumeClaim: 
            claimName: {{ include "simple-web-server.fullname" . }}-data
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: {{ include "simple-web-server.fullname" . }}-data
              mountPath: /usr/share/nginx/html
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
