apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: app
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000