apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttrss-db
spec:
  selector:
    matchLabels:
      app: ttrss-db
  template:
    metadata:
      labels:
        app: ttrss-db
    spec:
      volumes:
        - name: ttrss-db
          persistentVolumeClaim:
            claimName: ttrss-db
      containers:
        - name: ttrss-db
          image: "postgres:{{ .Values.postgres.version }}"
          volumeMounts:
            - name: ttrss-db
              mountPath: /var/lib/postgresql/data
          ports:
            - name: tcp
              containerPort: 5432
              protocol: TCP
            - name: udp
              containerPort: 5432
              protocol: UDP
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
              # see https://github.com/docker-library/postgres/issues/116#issuecomment-490241287
              # If this is a mounted NFS share, no_root_squash should be specified.
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata