apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db
      containers:
        - name: db
          image: "postgres:{{ .Values.postgres.version }}"
          volumeMounts:
            - name: db
              mountPath: /var/lib/postgresql/data
          ports:
            - name: tcp
              containerPort: 5432
              protocol: TCP
            - name: udp
              containerPort: 5432
              protocol: UDP
          resources:
            limits:
              memory: "256M"
          env:
            - name: POSTGRES_DB
              value: ttrss
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_username
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: secrets
                  key: db_password
              # see https://github.com/docker-library/postgres/issues/116#issuecomment-490241287
              # If this is a mounted NFS share, no_root_squash should be specified.
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
