apiVersion: v1
kind: Service
metadata:
  name: ttrss-db
spec:
  selector:
    app: ttrss-db
  type: ClusterIP
  ports:
    - name: tcp
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: udp
      protocol: UDP
      port: 5432
      targetPort: 5432