apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
    - name: tcp
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: udp
      protocol: UDP
      port: 5432
      targetPort: 5432