apiVersion: apps/v1
kind: Deployment
metadata:
  name: updater
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: updater
  template:
    metadata:
      labels:
        app: updater
    spec:
      volumes:
        - name: app
          persistentVolumeClaim:
            claimName: app
      containers:
        - name: updater
          image: cthulhoo/ttrss-fpm-pgsql-static
          volumeMounts:
            - name: app
              mountPath: /var/www/html
          resources:
            limits:
              cpu: "2"
              memory: "256M"
          env:
            - name: DB_TYPE
              value: pgsql
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: ttrss
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_username
            - name: DB_PASS
              valueFrom: 
                secretKeyRef:
                  name: secrets
                  key: db_password
            - name: OWNER_UID
              value: "1000"
            - name: OWNER_GID
              value: "1000"
            - name: SELF_URL_PATH
              value: {{ .Values.ttrss.url }}
          command: ["/updater.sh"]