apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 2015
      targetPort: 2015
      nodePort: {{ .Values.ttrss.nodePort }}