# Create persistent volume to access nginx data via NFS
# TODO: This should be defined more generally for the while cluster.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-data
spec:
  storageClassName: nfs
  capacity:
    storage: 10G
  accessModes:
    - ReadOnlyMany
  nfs:
    path: /volume2/k8s/html
    server: ds.fritz.box
---
# Create namespace 'nginx'
apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
# Create PVC for nginx data volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-data
  namespace: nginx
spec:
  storageClassName: nfs
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10M
---
# Create deployment 'nginx'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-data
          persistentVolumeClaim:
              claimName: nginx-data
      containers:
        - image: nginx:latest
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-data
              mountPath: /usr/share/nginx/html
          resources:
            limits:
              memory: 2G
              cpu: 1000m
            requests:
              memory: 1G
              cpu: 500m  
---
# Create service 'nginx' to access nginx pods
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    name: http
    nodePort: 30080