# Create persistent volume to access nginx data via NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-data
spec:
  storageClassName: nfs
  capacity:
    storage: 10G
  accessModes:
    - ReadOnlyMany
  nfs:
    path: /volume2/k8s/html
    server: ds.fritz.box